// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import grpc "google.golang.org/grpc"
import mock "github.com/stretchr/testify/mock"
import proto "github.com/JaneKetko/Buses/api/proto"

// BusesManagerClient is an autogenerated mock type for the BusesManagerClient type
type BusesManagerClient struct {
	mock.Mock
}

// BuyTicket provides a mock function with given fields: ctx, in, opts
func (_m *BusesManagerClient) BuyTicket(ctx context.Context, in *proto.IDRequest, opts ...grpc.CallOption) (*proto.TicketResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *proto.TicketResponse
	if rf, ok := ret.Get(0).(func(context.Context, *proto.IDRequest, ...grpc.CallOption) *proto.TicketResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.TicketResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.IDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateRoute provides a mock function with given fields: ctx, in, opts
func (_m *BusesManagerClient) CreateRoute(ctx context.Context, in *proto.SingleRoute, opts ...grpc.CallOption) (*proto.Nothing, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *proto.Nothing
	if rf, ok := ret.Get(0).(func(context.Context, *proto.SingleRoute, ...grpc.CallOption) *proto.Nothing); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.Nothing)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.SingleRoute, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteRoute provides a mock function with given fields: ctx, in, opts
func (_m *BusesManagerClient) DeleteRoute(ctx context.Context, in *proto.IDRequest, opts ...grpc.CallOption) (*proto.Nothing, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *proto.Nothing
	if rf, ok := ret.Get(0).(func(context.Context, *proto.IDRequest, ...grpc.CallOption) *proto.Nothing); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.Nothing)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.IDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoute provides a mock function with given fields: ctx, in, opts
func (_m *BusesManagerClient) GetRoute(ctx context.Context, in *proto.IDRequest, opts ...grpc.CallOption) (*proto.SingleRoute, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *proto.SingleRoute
	if rf, ok := ret.Get(0).(func(context.Context, *proto.IDRequest, ...grpc.CallOption) *proto.SingleRoute); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.SingleRoute)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.IDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoutes provides a mock function with given fields: ctx, in, opts
func (_m *BusesManagerClient) GetRoutes(ctx context.Context, in *proto.Nothing, opts ...grpc.CallOption) (*proto.ListRoutes, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *proto.ListRoutes
	if rf, ok := ret.Get(0).(func(context.Context, *proto.Nothing, ...grpc.CallOption) *proto.ListRoutes); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.ListRoutes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.Nothing, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchRoutes provides a mock function with given fields: ctx, in, opts
func (_m *BusesManagerClient) SearchRoutes(ctx context.Context, in *proto.Search, opts ...grpc.CallOption) (*proto.ListRoutes, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *proto.ListRoutes
	if rf, ok := ret.Get(0).(func(context.Context, *proto.Search, ...grpc.CallOption) *proto.ListRoutes); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.ListRoutes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.Search, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
