// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpcserver.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Search struct {
	StartTime            string   `protobuf:"bytes,1,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndPoint             string   `protobuf:"bytes,2,opt,name=EndPoint,proto3" json:"EndPoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Search) Reset()         { *m = Search{} }
func (m *Search) String() string { return proto.CompactTextString(m) }
func (*Search) ProtoMessage()    {}
func (*Search) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa6debe97205904, []int{0}
}

func (m *Search) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Search.Unmarshal(m, b)
}
func (m *Search) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Search.Marshal(b, m, deterministic)
}
func (m *Search) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Search.Merge(m, src)
}
func (m *Search) XXX_Size() int {
	return xxx_messageInfo_Search.Size(m)
}
func (m *Search) XXX_DiscardUnknown() {
	xxx_messageInfo_Search.DiscardUnknown(m)
}

var xxx_messageInfo_Search proto.InternalMessageInfo

func (m *Search) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *Search) GetEndPoint() string {
	if m != nil {
		return m.EndPoint
	}
	return ""
}

type Nothing struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nothing) Reset()         { *m = Nothing{} }
func (m *Nothing) String() string { return proto.CompactTextString(m) }
func (*Nothing) ProtoMessage()    {}
func (*Nothing) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa6debe97205904, []int{1}
}

func (m *Nothing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nothing.Unmarshal(m, b)
}
func (m *Nothing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nothing.Marshal(b, m, deterministic)
}
func (m *Nothing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nothing.Merge(m, src)
}
func (m *Nothing) XXX_Size() int {
	return xxx_messageInfo_Nothing.Size(m)
}
func (m *Nothing) XXX_DiscardUnknown() {
	xxx_messageInfo_Nothing.DiscardUnknown(m)
}

var xxx_messageInfo_Nothing proto.InternalMessageInfo

type SingleRoute struct {
	Route                *BusRoute `protobuf:"bytes,1,opt,name=Route,proto3" json:"Route,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SingleRoute) Reset()         { *m = SingleRoute{} }
func (m *SingleRoute) String() string { return proto.CompactTextString(m) }
func (*SingleRoute) ProtoMessage()    {}
func (*SingleRoute) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa6debe97205904, []int{2}
}

func (m *SingleRoute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleRoute.Unmarshal(m, b)
}
func (m *SingleRoute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleRoute.Marshal(b, m, deterministic)
}
func (m *SingleRoute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleRoute.Merge(m, src)
}
func (m *SingleRoute) XXX_Size() int {
	return xxx_messageInfo_SingleRoute.Size(m)
}
func (m *SingleRoute) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleRoute.DiscardUnknown(m)
}

var xxx_messageInfo_SingleRoute proto.InternalMessageInfo

func (m *SingleRoute) GetRoute() *BusRoute {
	if m != nil {
		return m.Route
	}
	return nil
}

type IDRequest struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IDRequest) Reset()         { *m = IDRequest{} }
func (m *IDRequest) String() string { return proto.CompactTextString(m) }
func (*IDRequest) ProtoMessage()    {}
func (*IDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa6debe97205904, []int{3}
}

func (m *IDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDRequest.Unmarshal(m, b)
}
func (m *IDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDRequest.Marshal(b, m, deterministic)
}
func (m *IDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDRequest.Merge(m, src)
}
func (m *IDRequest) XXX_Size() int {
	return xxx_messageInfo_IDRequest.Size(m)
}
func (m *IDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IDRequest proto.InternalMessageInfo

func (m *IDRequest) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type ListRoutes struct {
	BusRoutes            []*BusRoute `protobuf:"bytes,1,rep,name=BusRoutes,proto3" json:"BusRoutes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListRoutes) Reset()         { *m = ListRoutes{} }
func (m *ListRoutes) String() string { return proto.CompactTextString(m) }
func (*ListRoutes) ProtoMessage()    {}
func (*ListRoutes) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa6debe97205904, []int{4}
}

func (m *ListRoutes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRoutes.Unmarshal(m, b)
}
func (m *ListRoutes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRoutes.Marshal(b, m, deterministic)
}
func (m *ListRoutes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRoutes.Merge(m, src)
}
func (m *ListRoutes) XXX_Size() int {
	return xxx_messageInfo_ListRoutes.Size(m)
}
func (m *ListRoutes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRoutes.DiscardUnknown(m)
}

var xxx_messageInfo_ListRoutes proto.InternalMessageInfo

func (m *ListRoutes) GetBusRoutes() []*BusRoute {
	if m != nil {
		return m.BusRoutes
	}
	return nil
}

type BusRoute struct {
	ID                   int64                `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Points               *RoutePoints         `protobuf:"bytes,2,opt,name=Points,proto3" json:"Points,omitempty"`
	Start                *timestamp.Timestamp `protobuf:"bytes,3,opt,name=Start,proto3" json:"Start,omitempty"`
	Cost                 int64                `protobuf:"varint,4,opt,name=Cost,proto3" json:"Cost,omitempty"`
	FreeSeats            int64                `protobuf:"varint,5,opt,name=FreeSeats,proto3" json:"FreeSeats,omitempty"`
	AllSeats             int64                `protobuf:"varint,6,opt,name=AllSeats,proto3" json:"AllSeats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BusRoute) Reset()         { *m = BusRoute{} }
func (m *BusRoute) String() string { return proto.CompactTextString(m) }
func (*BusRoute) ProtoMessage()    {}
func (*BusRoute) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa6debe97205904, []int{5}
}

func (m *BusRoute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BusRoute.Unmarshal(m, b)
}
func (m *BusRoute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BusRoute.Marshal(b, m, deterministic)
}
func (m *BusRoute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusRoute.Merge(m, src)
}
func (m *BusRoute) XXX_Size() int {
	return xxx_messageInfo_BusRoute.Size(m)
}
func (m *BusRoute) XXX_DiscardUnknown() {
	xxx_messageInfo_BusRoute.DiscardUnknown(m)
}

var xxx_messageInfo_BusRoute proto.InternalMessageInfo

func (m *BusRoute) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *BusRoute) GetPoints() *RoutePoints {
	if m != nil {
		return m.Points
	}
	return nil
}

func (m *BusRoute) GetStart() *timestamp.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *BusRoute) GetCost() int64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *BusRoute) GetFreeSeats() int64 {
	if m != nil {
		return m.FreeSeats
	}
	return 0
}

func (m *BusRoute) GetAllSeats() int64 {
	if m != nil {
		return m.AllSeats
	}
	return 0
}

type RoutePoints struct {
	StartPoint           string   `protobuf:"bytes,1,opt,name=StartPoint,proto3" json:"StartPoint,omitempty"`
	EndPoint             string   `protobuf:"bytes,2,opt,name=EndPoint,proto3" json:"EndPoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoutePoints) Reset()         { *m = RoutePoints{} }
func (m *RoutePoints) String() string { return proto.CompactTextString(m) }
func (*RoutePoints) ProtoMessage()    {}
func (*RoutePoints) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa6debe97205904, []int{6}
}

func (m *RoutePoints) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoutePoints.Unmarshal(m, b)
}
func (m *RoutePoints) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoutePoints.Marshal(b, m, deterministic)
}
func (m *RoutePoints) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoutePoints.Merge(m, src)
}
func (m *RoutePoints) XXX_Size() int {
	return xxx_messageInfo_RoutePoints.Size(m)
}
func (m *RoutePoints) XXX_DiscardUnknown() {
	xxx_messageInfo_RoutePoints.DiscardUnknown(m)
}

var xxx_messageInfo_RoutePoints proto.InternalMessageInfo

func (m *RoutePoints) GetStartPoint() string {
	if m != nil {
		return m.StartPoint
	}
	return ""
}

func (m *RoutePoints) GetEndPoint() string {
	if m != nil {
		return m.EndPoint
	}
	return ""
}

type TicketResponse struct {
	Ticket               *Ticket  `protobuf:"bytes,1,opt,name=Ticket,proto3" json:"Ticket,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TicketResponse) Reset()         { *m = TicketResponse{} }
func (m *TicketResponse) String() string { return proto.CompactTextString(m) }
func (*TicketResponse) ProtoMessage()    {}
func (*TicketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa6debe97205904, []int{7}
}

func (m *TicketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TicketResponse.Unmarshal(m, b)
}
func (m *TicketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TicketResponse.Marshal(b, m, deterministic)
}
func (m *TicketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TicketResponse.Merge(m, src)
}
func (m *TicketResponse) XXX_Size() int {
	return xxx_messageInfo_TicketResponse.Size(m)
}
func (m *TicketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TicketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TicketResponse proto.InternalMessageInfo

func (m *TicketResponse) GetTicket() *Ticket {
	if m != nil {
		return m.Ticket
	}
	return nil
}

type Ticket struct {
	Points               *RoutePoints         `protobuf:"bytes,1,opt,name=Points,proto3" json:"Points,omitempty"`
	Start                *timestamp.Timestamp `protobuf:"bytes,2,opt,name=Start,proto3" json:"Start,omitempty"`
	Cost                 int64                `protobuf:"varint,3,opt,name=Cost,proto3" json:"Cost,omitempty"`
	Place                int64                `protobuf:"varint,4,opt,name=Place,proto3" json:"Place,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Ticket) Reset()         { *m = Ticket{} }
func (m *Ticket) String() string { return proto.CompactTextString(m) }
func (*Ticket) ProtoMessage()    {}
func (*Ticket) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa6debe97205904, []int{8}
}

func (m *Ticket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ticket.Unmarshal(m, b)
}
func (m *Ticket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ticket.Marshal(b, m, deterministic)
}
func (m *Ticket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ticket.Merge(m, src)
}
func (m *Ticket) XXX_Size() int {
	return xxx_messageInfo_Ticket.Size(m)
}
func (m *Ticket) XXX_DiscardUnknown() {
	xxx_messageInfo_Ticket.DiscardUnknown(m)
}

var xxx_messageInfo_Ticket proto.InternalMessageInfo

func (m *Ticket) GetPoints() *RoutePoints {
	if m != nil {
		return m.Points
	}
	return nil
}

func (m *Ticket) GetStart() *timestamp.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Ticket) GetCost() int64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *Ticket) GetPlace() int64 {
	if m != nil {
		return m.Place
	}
	return 0
}

func init() {
	proto.RegisterType((*Search)(nil), "proto.Search")
	proto.RegisterType((*Nothing)(nil), "proto.Nothing")
	proto.RegisterType((*SingleRoute)(nil), "proto.SingleRoute")
	proto.RegisterType((*IDRequest)(nil), "proto.IDRequest")
	proto.RegisterType((*ListRoutes)(nil), "proto.ListRoutes")
	proto.RegisterType((*BusRoute)(nil), "proto.BusRoute")
	proto.RegisterType((*RoutePoints)(nil), "proto.RoutePoints")
	proto.RegisterType((*TicketResponse)(nil), "proto.TicketResponse")
	proto.RegisterType((*Ticket)(nil), "proto.Ticket")
}

func init() { proto.RegisterFile("grpcserver.proto", fileDescriptor_afa6debe97205904) }

var fileDescriptor_afa6debe97205904 = []byte{
	// 483 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xe1, 0x8a, 0xd3, 0x40,
	0x10, 0x26, 0xe9, 0x25, 0x36, 0x93, 0xb3, 0x9e, 0x8b, 0x42, 0x88, 0xa2, 0x47, 0x40, 0x10, 0xc1,
	0xb4, 0xd6, 0x03, 0x7f, 0xf8, 0xcb, 0x5e, 0x55, 0x0a, 0x2a, 0x47, 0xda, 0x17, 0xd8, 0xab, 0x63,
	0x2e, 0x98, 0x66, 0xeb, 0xee, 0x46, 0xf0, 0x2d, 0x7c, 0x20, 0x7f, 0xfb, 0x5c, 0xd2, 0xd9, 0xdd,
	0x36, 0xf6, 0x8a, 0x78, 0xbf, 0x92, 0x99, 0xef, 0xdb, 0x99, 0x9d, 0xef, 0x9b, 0x85, 0x93, 0x52,
	0xae, 0x97, 0x0a, 0xe5, 0x77, 0x94, 0xf9, 0x5a, 0x0a, 0x2d, 0x58, 0x40, 0x9f, 0xf4, 0x71, 0x29,
	0x44, 0x59, 0xe3, 0x90, 0xa2, 0xcb, 0xf6, 0xcb, 0x50, 0x57, 0x2b, 0x54, 0x9a, 0xaf, 0xd6, 0x86,
	0x97, 0x4d, 0x20, 0x9c, 0x23, 0x97, 0xcb, 0x2b, 0xf6, 0x10, 0xa2, 0xb9, 0xe6, 0x52, 0x2f, 0xaa,
	0x15, 0x26, 0xde, 0xa9, 0xf7, 0x34, 0x2a, 0x76, 0x09, 0x96, 0x42, 0xff, 0x6d, 0xf3, 0xf9, 0x42,
	0x54, 0x8d, 0x4e, 0x7c, 0x02, 0xb7, 0x71, 0x16, 0xc1, 0xad, 0x4f, 0x42, 0x5f, 0x55, 0x4d, 0x99,
	0x9d, 0x41, 0x3c, 0xaf, 0x9a, 0xb2, 0xc6, 0x42, 0xb4, 0x1a, 0xd9, 0x13, 0x08, 0xe8, 0x87, 0xea,
	0xc5, 0xe3, 0x3b, 0xa6, 0x69, 0x3e, 0x69, 0x15, 0xa5, 0x0b, 0x83, 0x66, 0x0f, 0x20, 0x9a, 0x4d,
	0x0b, 0xfc, 0xd6, 0xa2, 0xd2, 0x6c, 0x00, 0xfe, 0x6c, 0x4a, 0x07, 0x7a, 0x85, 0x3f, 0x9b, 0x66,
	0xaf, 0x01, 0x3e, 0x54, 0x4a, 0x13, 0x53, 0xb1, 0xe7, 0x10, 0xb9, 0xd3, 0x2a, 0xf1, 0x4e, 0x7b,
	0x87, 0xaa, 0xee, 0x18, 0xd9, 0x6f, 0x0f, 0xfa, 0x2e, 0xda, 0xaf, 0xcc, 0x9e, 0x41, 0x48, 0x03,
	0x28, 0x9a, 0x28, 0x1e, 0x33, 0x5b, 0x88, 0xd8, 0x06, 0x29, 0x2c, 0x83, 0x8d, 0x20, 0x20, 0x31,
	0x92, 0x1e, 0x51, 0xd3, 0xdc, 0x08, 0x9b, 0x3b, 0x61, 0xf3, 0x85, 0x13, 0xb6, 0x30, 0x44, 0xc6,
	0xe0, 0xe8, 0x5c, 0x28, 0x9d, 0x1c, 0x51, 0x3f, 0xfa, 0xdf, 0x68, 0xfc, 0x4e, 0x22, 0xce, 0x91,
	0x6b, 0x95, 0x04, 0x04, 0xec, 0x12, 0x1b, 0x8d, 0xdf, 0xd4, 0xb5, 0x01, 0x43, 0x02, 0xb7, 0x71,
	0x36, 0x83, 0xb8, 0x73, 0x2d, 0xf6, 0x08, 0x80, 0xba, 0x18, 0x43, 0x8c, 0x5b, 0x9d, 0xcc, 0x3f,
	0xed, 0x7a, 0x05, 0x83, 0x45, 0xb5, 0xfc, 0x8a, 0xba, 0x40, 0xb5, 0x16, 0x8d, 0xda, 0xd8, 0x14,
	0x9a, 0x8c, 0xf5, 0xe9, 0xb6, 0x15, 0xc2, 0xd2, 0x2c, 0x98, 0xfd, 0xf4, 0x1c, 0xaf, 0x23, 0x9d,
	0xf7, 0xff, 0xd2, 0xf9, 0x37, 0x95, 0xae, 0xd7, 0x91, 0xee, 0x1e, 0x04, 0x17, 0x35, 0x5f, 0xa2,
	0xd5, 0xd3, 0x04, 0xe3, 0x5f, 0x3e, 0x1c, 0x4f, 0x5a, 0x85, 0xea, 0x23, 0x6f, 0x78, 0x89, 0x92,
	0xe5, 0x10, 0xbd, 0x47, 0xb7, 0x2c, 0x03, 0x7b, 0x2b, 0xbb, 0x9d, 0xe9, 0x5d, 0x1b, 0x77, 0xf6,
	0x69, 0x04, 0x7d, 0xc7, 0x67, 0x27, 0x16, 0xde, 0xee, 0x62, 0xea, 0xc6, 0xea, 0xee, 0xf4, 0x0b,
	0x88, 0xcf, 0x25, 0x72, 0x6d, 0xc3, 0x03, 0x94, 0x74, 0xaf, 0x2f, 0x1b, 0x42, 0x3c, 0xc5, 0x1a,
	0xdd, 0x91, 0xeb, 0x7d, 0xf6, 0x0f, 0x8c, 0xe0, 0xd8, 0xbc, 0x4a, 0x7b, 0x4b, 0x67, 0x88, 0x49,
	0x1e, 0x9a, 0xe3, 0x6c, 0xf3, 0x2e, 0x7e, 0x58, 0x77, 0xae, 0x37, 0xb8, 0xff, 0xb7, 0xa3, 0xd6,
	0xf8, 0xcb, 0x90, 0xb2, 0x2f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x69, 0x63, 0xce, 0x18, 0x40,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BusesManagerClient is the client API for BusesManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BusesManagerClient interface {
	GetRoutes(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*ListRoutes, error)
	GetRoute(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*SingleRoute, error)
	CreateRoute(ctx context.Context, in *SingleRoute, opts ...grpc.CallOption) (*Nothing, error)
	DeleteRoute(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*Nothing, error)
	SearchRoutes(ctx context.Context, in *Search, opts ...grpc.CallOption) (*ListRoutes, error)
	BuyTicket(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*TicketResponse, error)
}

type busesManagerClient struct {
	cc *grpc.ClientConn
}

func NewBusesManagerClient(cc *grpc.ClientConn) BusesManagerClient {
	return &busesManagerClient{cc}
}

func (c *busesManagerClient) GetRoutes(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*ListRoutes, error) {
	out := new(ListRoutes)
	err := c.cc.Invoke(ctx, "/proto.BusesManager/GetRoutes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *busesManagerClient) GetRoute(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*SingleRoute, error) {
	out := new(SingleRoute)
	err := c.cc.Invoke(ctx, "/proto.BusesManager/GetRoute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *busesManagerClient) CreateRoute(ctx context.Context, in *SingleRoute, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/proto.BusesManager/CreateRoute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *busesManagerClient) DeleteRoute(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/proto.BusesManager/DeleteRoute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *busesManagerClient) SearchRoutes(ctx context.Context, in *Search, opts ...grpc.CallOption) (*ListRoutes, error) {
	out := new(ListRoutes)
	err := c.cc.Invoke(ctx, "/proto.BusesManager/SearchRoutes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *busesManagerClient) BuyTicket(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*TicketResponse, error) {
	out := new(TicketResponse)
	err := c.cc.Invoke(ctx, "/proto.BusesManager/BuyTicket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BusesManagerServer is the server API for BusesManager service.
type BusesManagerServer interface {
	GetRoutes(context.Context, *Nothing) (*ListRoutes, error)
	GetRoute(context.Context, *IDRequest) (*SingleRoute, error)
	CreateRoute(context.Context, *SingleRoute) (*Nothing, error)
	DeleteRoute(context.Context, *IDRequest) (*Nothing, error)
	SearchRoutes(context.Context, *Search) (*ListRoutes, error)
	BuyTicket(context.Context, *IDRequest) (*TicketResponse, error)
}

// UnimplementedBusesManagerServer can be embedded to have forward compatible implementations.
type UnimplementedBusesManagerServer struct {
}

func (*UnimplementedBusesManagerServer) GetRoutes(ctx context.Context, req *Nothing) (*ListRoutes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoutes not implemented")
}
func (*UnimplementedBusesManagerServer) GetRoute(ctx context.Context, req *IDRequest) (*SingleRoute, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoute not implemented")
}
func (*UnimplementedBusesManagerServer) CreateRoute(ctx context.Context, req *SingleRoute) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoute not implemented")
}
func (*UnimplementedBusesManagerServer) DeleteRoute(ctx context.Context, req *IDRequest) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRoute not implemented")
}
func (*UnimplementedBusesManagerServer) SearchRoutes(ctx context.Context, req *Search) (*ListRoutes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchRoutes not implemented")
}
func (*UnimplementedBusesManagerServer) BuyTicket(ctx context.Context, req *IDRequest) (*TicketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyTicket not implemented")
}

func RegisterBusesManagerServer(s *grpc.Server, srv BusesManagerServer) {
	s.RegisterService(&_BusesManager_serviceDesc, srv)
}

func _BusesManager_GetRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nothing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusesManagerServer).GetRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BusesManager/GetRoutes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusesManagerServer).GetRoutes(ctx, req.(*Nothing))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusesManager_GetRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusesManagerServer).GetRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BusesManager/GetRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusesManagerServer).GetRoute(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusesManager_CreateRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingleRoute)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusesManagerServer).CreateRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BusesManager/CreateRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusesManagerServer).CreateRoute(ctx, req.(*SingleRoute))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusesManager_DeleteRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusesManagerServer).DeleteRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BusesManager/DeleteRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusesManagerServer).DeleteRoute(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusesManager_SearchRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Search)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusesManagerServer).SearchRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BusesManager/SearchRoutes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusesManagerServer).SearchRoutes(ctx, req.(*Search))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusesManager_BuyTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusesManagerServer).BuyTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BusesManager/BuyTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusesManagerServer).BuyTicket(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BusesManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BusesManager",
	HandlerType: (*BusesManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRoutes",
			Handler:    _BusesManager_GetRoutes_Handler,
		},
		{
			MethodName: "GetRoute",
			Handler:    _BusesManager_GetRoute_Handler,
		},
		{
			MethodName: "CreateRoute",
			Handler:    _BusesManager_CreateRoute_Handler,
		},
		{
			MethodName: "DeleteRoute",
			Handler:    _BusesManager_DeleteRoute_Handler,
		},
		{
			MethodName: "SearchRoutes",
			Handler:    _BusesManager_SearchRoutes_Handler,
		},
		{
			MethodName: "BuyTicket",
			Handler:    _BusesManager_BuyTicket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcserver.proto",
}
